name = "Processes"
uuid = "6a369836-0793-447d-b7ee-625716f2d05b"
authors = ["Fabian IJpelaar <87425229+f-ij@users.noreply.github.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
BenchmarkTools = "1.6.0"
InteractiveUtils = "1.11.0"
MacroTools = "0.5.15"
UUIDs = "1.11.0"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[targets]
tests = ["BenchmarkTools"]
