"""
Turn `@init((; ...))` into a keyword assignment `_init = (; ...)`.

This is primarily meant for the bootstrap call style generated by `@ProcessAlgorithm`,
for example:

```julia
MyAlgo(input; @init((; n = 10)))
```
"""
macro init(ex)
    return Expr(:kw, :_init, esc(ex))
end

"""
Turn `@inputs((; ...))` into a keyword assignment `_init = (; ...)`.

This is the clearer public alias for the init-time input declarations consumed by
`@ProcessAlgorithm`.
"""
macro inputs(ex)
    return Expr(:kw, :_init, esc(ex))
end

_pa_is_macrocall(ex, names::Symbol...) =
    ex isa Expr && ex.head == :macrocall && any(name -> ex.args[1] == name, names)

_pa_is_inputs_macro(ex) = _pa_is_macrocall(ex, Symbol("@init"), Symbol("@inputs"))

function _pa_binding_parts(ex)
    if ex isa Symbol
        return ex, nothing
    elseif ex isa Expr && ex.head == :(::)
        return ex.args[1], ex.args[2]
    end
    error("Unsupported argument declaration: $ex")
end

_pa_binding_expr(name::Symbol, typeexpr) = isnothing(typeexpr) ? name : Expr(:(::), name, typeexpr)

function _pa_parse_kw_decl(ex)
    @assert ex isa Expr && ex.head == :kw "Expected keyword declaration, got $ex"
    name, typeexpr = _pa_binding_parts(ex.args[1])
    return (; name, typeexpr, default = ex.args[2])
end

function _pa_parse_init_tuple(ex)
    ex isa Expr && ex.head == :tuple || error("@inputs/@init expects a named tuple style payload, got $ex")
    !isempty(ex.args) || return NamedTuple[]
    params = ex.args[1]
    params isa Expr && params.head == :parameters || error("@inputs/@init expects a named tuple style payload, got $ex")

    fields = NamedTuple[]
    for arg in params.args
        if arg isa Expr && arg.head == :kw
            name, typeexpr = _pa_binding_parts(arg.args[1])
            push!(fields, (; name, typeexpr, default = arg.args[2], required = false))
        else
            name, typeexpr = _pa_binding_parts(arg)
            push!(fields, (; name, typeexpr, default = nothing, required = true))
        end
    end
    return fields
end

function _pa_parse_positional_arg(ex)
    if _pa_is_macrocall(ex, Symbol("@managed"))
        inner = ex.args[end]
        if inner isa Expr && inner.head == :(=)
            name, typeexpr = _pa_binding_parts(inner.args[1])
            return (; kind = :managed, name, typeexpr, default = inner.args[2], capture_input = false)
        end
        name, typeexpr = _pa_binding_parts(inner)
        return (; kind = :managed, name, typeexpr, default = nothing, capture_input = true)
    elseif ex isa Expr && ex.head == :(=)
        error("Only @managed positional arguments may have defaults, got $ex")
    else
        name, typeexpr = _pa_binding_parts(ex)
        return (; kind = :plain, name, typeexpr, default = nothing, capture_input = false)
    end
end

function _pa_new_parse_signature(call_ex)
    call_ex isa Expr && call_ex.head == :call || error("@ProcessAlgorithmNew expects a function definition")

    fname = call_ex.args[1]
    args = call_ex.args[2:end]
    params = nothing
    if !isempty(args) && args[1] isa Expr && args[1].head == :parameters
        params = args[1]
        args = args[2:end]
    end

    positional = map(_pa_parse_positional_arg, args)
    plain_pos = filter(x -> x.kind == :plain, positional)
    managed_pos = filter(x -> x.kind == :managed, positional)

    normal_kwargs = NamedTuple[]
    input_fields = NamedTuple[]
    if !isnothing(params)
        for (idx, arg) in enumerate(params.args)
            if _pa_is_inputs_macro(arg)
                idx == length(params.args) || error("@inputs/@init must be the last keyword-like argument in @ProcessAlgorithm")
                isempty(input_fields) || error("Only one @inputs/@init block is allowed in @ProcessAlgorithm")
                input_fields = _pa_parse_init_tuple(arg.args[end])
            else
                push!(normal_kwargs, _pa_parse_kw_decl(arg))
            end
        end
    end

    return (; fname, positional, plain_pos, managed_pos, normal_kwargs, input_fields)
end

_pa_local_get_expr(ctx, name::Symbol, default) = :(get($ctx, $(QuoteNode(name)), $default))

function _pa_required_get_expr(ctx, name::Symbol)
    quote
        if !haskey($ctx, $(QuoteNode(name)))
            error("Missing required input $(string($(QuoteNode(name))))")
        end
        getproperty($ctx, $(QuoteNode(name)))
    end
end

function _pa_typed_assignment(name::Symbol, typeexpr, value_expr)
    if isnothing(typeexpr)
        return :(local $name = $value_expr)
    end
    return :(local $(Expr(:(::), name, typeexpr)) = $value_expr)
end

function _pa_input_assignment_exprs(field, ctxsym, tempsym)
    getexpr = field.required ? _pa_required_get_expr(ctxsym, field.name) : _pa_local_get_expr(ctxsym, field.name, field.default)
    return Any[
        :(local $tempsym = $getexpr),
        _pa_typed_assignment(field.name, field.typeexpr, tempsym),
    ]
end

function _pa_managed_assignment(field, input_temps)
    value_expr = field.capture_input ? input_temps[field.name] : field.default
    return _pa_typed_assignment(field.name, field.typeexpr, value_expr)
end

function _pa_runtime_kw_assignment(field, ctxsym)
    getexpr = _pa_local_get_expr(ctxsym, field.name, field.default)
    return _pa_typed_assignment(field.name, field.typeexpr, getexpr)
end

function _pa_runtime_pos_assignment(field, ctxsym)
    return _pa_typed_assignment(field.name, field.typeexpr, :(getproperty($ctxsym, $(QuoteNode(field.name)))))
end

"""
Function-first ProcessAlgorithm definition with explicit managed runtime state and init-only
inputs.

Supported surface syntax:

```julia
@ProcessAlgorithm function MyAlgo(
    input_signal,
    @managed(state = 0.0);
    gain::Float64 = 1.0,
    @inputs((; n::Int, scale0::Float64 = 1.0))
)
    ...
end
```

`@managed(...)` marks positional arguments that live in the local subcontext and are created by
`Processes.init`. `@managed(name)` captures a same-named declared input into local state. The
trailing `@inputs((; ...))` block declares init-only inputs that may be
provided through the process context or through the standalone bootstrap call
`MyAlgo(...; @inputs((; ...)))`.
"""
macro ProcessAlgorithm(ex)
    ex isa Expr && ex.head == :function || error("@ProcessAlgorithm expects a function definition")

    signature = _pa_new_parse_signature(ex.args[1])
    body = ex.args[2]

    fname = signature.fname
    impl_name = gensym(Symbol(fname, :_impl))
    input_names = Set(field.name for field in signature.input_fields)
    for field in signature.managed_pos
        if field.capture_input && !(field.name in input_names)
            error("`@managed($(field.name))` requires `$(field.name)` to be declared in @inputs/@init")
        end
    end
    input_temps = Dict(field.name => gensym(Symbol(field.name, :_input)) for field in signature.input_fields)

    positional_bindings = [_pa_binding_expr(arg.name, arg.typeexpr) for arg in signature.positional]
    plain_pos_bindings = [_pa_binding_expr(arg.name, arg.typeexpr) for arg in signature.plain_pos]
    kw_bindings = [Expr(:kw, _pa_binding_expr(kw.name, kw.typeexpr), kw.default) for kw in signature.normal_kwargs]

    impl_signature = Expr(:call, impl_name, positional_bindings...)
    if !isempty(kw_bindings)
        insert!(impl_signature.args, 2, Expr(:parameters, kw_bindings...))
    end

    impl_def = Expr(:function, impl_signature, body)

    public_piped_signature = Expr(:call, fname, positional_bindings...)
    piped_kw_bindings = copy(kw_bindings)
    push!(piped_kw_bindings, Expr(:kw, :_init, nothing))
    insert!(public_piped_signature.args, 2, Expr(:parameters, piped_kw_bindings...))
    piped_kw_forward = [Expr(:kw, kw.name, kw.name) for kw in signature.normal_kwargs]
    piped_def = Expr(:function, public_piped_signature, quote
            if !isnothing(_init)
                error("Cannot pass both managed positional arguments and @inputs/@init values to $(string($fname))")
            end
            return $impl_name($(map(x -> x.name, signature.positional)...); $(piped_kw_forward...))
        end)

    bootstrap_signature = Expr(:call, fname, plain_pos_bindings...)
    bootstrap_kw_bindings = copy(kw_bindings)
    push!(bootstrap_kw_bindings, Expr(:kw, :_init, Expr(:tuple, Expr(:parameters))))
    insert!(bootstrap_signature.args, 2, Expr(:parameters, bootstrap_kw_bindings...))
    bootstrap_input_assignments = Any[]
    for field in signature.input_fields
        append!(bootstrap_input_assignments, _pa_input_assignment_exprs(field, :_init, input_temps[field.name]))
    end
    bootstrap_managed_assignments = [_pa_managed_assignment(field, input_temps) for field in signature.managed_pos]
    bootstrap_kw_forward = [Expr(:kw, kw.name, kw.name) for kw in signature.normal_kwargs]
    bootstrap_call_args = [arg.name for arg in signature.plain_pos]
    append!(bootstrap_call_args, [arg.name for arg in signature.managed_pos])
    bootstrap_def = Expr(:function, bootstrap_signature, quote
            $(bootstrap_input_assignments...)
            $(bootstrap_managed_assignments...)
            return $impl_name($(bootstrap_call_args...); $(bootstrap_kw_forward...))
        end)

    input_assignments = Any[]
    for field in signature.input_fields
        append!(input_assignments, _pa_input_assignment_exprs(field, :context, input_temps[field.name]))
    end
    managed_assignments = [_pa_managed_assignment(field, input_temps) for field in signature.managed_pos]
    managed_tuple_expr = Expr(:tuple, Expr(:parameters, [Expr(:kw, field.name, field.name) for field in signature.managed_pos]...))
    init_def = quote
        function Processes.init(_algo::$fname, context::C) where {C <: Union{Processes.AbstractContext, NamedTuple}}
            $(input_assignments...)
            $(managed_assignments...)
            return $managed_tuple_expr
        end
    end

    step_pos_assignments = [_pa_runtime_pos_assignment(field, :context) for field in signature.positional]
    step_kw_assignments = [_pa_runtime_kw_assignment(field, :context) for field in signature.normal_kwargs]
    step_kw_forward = [Expr(:kw, kw.name, kw.name) for kw in signature.normal_kwargs]
    step_call_args = [arg.name for arg in signature.positional]
    step_def = quote
        function Processes.step!(_algo::$fname, context::C) where {C <: Union{Processes.AbstractContext, NamedTuple}}
            $(step_pos_assignments...)
            $(step_kw_assignments...)
            return $impl_name($(step_call_args...); $(step_kw_forward...))
        end
    end

    q = quote
        struct $fname <: Processes.ProcessAlgorithm end
        $impl_def
        $piped_def
        $bootstrap_def
        $init_def
        $step_def
    end
    # println(q)
    return esc(q)
end

export @ProcessAlgorithm, @init, @inputs
